/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: SebastianSosnowski (https://sketchfab.com/SebastianSosnowski)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-4de1bcbd22a444abb4f089b9b78ec96a
Title: Earth
*/

import React, { useRef, useMemo, useContext, createContext } from 'react'
import { useGLTF, Merged, useAnimations } from '@react-three/drei'

const context = createContext()
export function Instances({ children, ...props }) {
  const { nodes } = useGLTF('/models/earth(1).glb')
  const instances = useMemo(
    () => ({
      EarthMaterial: nodes['Earth_Material_#50_0'],
      EarthCloudsMaterial: nodes['EarthClouds_Material_#62_0'],
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export function Earth(props) {
  const instances = useContext(context)
  const group = useRef()
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          userData={{ name: 'Sketchfab_model' }}>
          <group
            name="3f0d8c1a7c7c45138e5b99b56838fcb9fbx"
            rotation={[Math.PI / 2, 0, 0]}
            userData={{ name: '3f0d8c1a7c7c45138e5b99b56838fcb9.fbx' }}>
            <group name="Object_2" userData={{ name: 'Object_2' }}>
              <group name="RootNode" userData={{ name: 'RootNode' }}>
                <group name="Earth" rotation={[-Math.PI / 2, 0, 0]} userData={{ name: 'Earth' }}>
                  <instances.EarthMaterial
                    name="Earth_Material_#50_0"
                    userData={{ name: 'Earth_Material #50_0' }}
                  />
                </group>
                <group
                  name="EarthClouds"
                  rotation={[-Math.PI / 2, -Math.PI / 9, 0]}
                  scale={1.01}
                  userData={{ name: 'EarthClouds' }}>
                  <instances.EarthCloudsMaterial
                    name="EarthClouds_Material_#62_0"
                    userData={{ name: 'EarthClouds_Material #62_0' }}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}


useGLTF.preload('/models/earth(1).glb')