/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: PatelDev (https://sketchfab.com/PatelDev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mars-0bbd08db494b4e2a873c624021248d12
Title: Mars
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Mars(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/mars.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials['Scene_-_Root']}
        scale={1.979}
      />
    </group>
  )
}

useGLTF.preload('/models/mars.glb')
