/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Recourse Design ltd. (https://sketchfab.com/RecourseDesign)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mercury-bc229dccc66b439ebe5fe4a80c4e535a
Title: Mercury
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Mercury(props) {
  const { nodes, materials } = useGLTF('/models/mercury.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Earth_Planet_0.geometry}
        material={materials.Planet}
      />
    </group>
  )
}

useGLTF.preload('/models/mercury.glb')
