/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Shady Tex (https://sketchfab.com/ShadyTex4u)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/realistic-uranus-4k-8efca1ce8038429fa0fc0a94a7468eae
Title: Realistic Uranus 4k
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Uranus(props) {
  const { nodes, materials } = useGLTF('/models/uranus.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere_Material_0.geometry}
          material={materials.Material}
          rotation={[-0.96, 0.253, 0.233]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_Material003_0.geometry}
          material={materials['Material.003']}
          rotation={[-1.318, 0.376, -0.179]}
          scale={899.348}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/uranus.glb')
